FROM quay.io/<%= ENV.fetch("FROM") %>
LABEL maintainer="Chet Bortz <chet@bortz.co>"

ENV RUBY_VERSION <%= ENV.fetch("RUBY_VERSION") %>
ENV RUBY_SHA1SUM <%= ENV.fetch("RUBY_SHA1SUM") %>
ENV RUBY_SUBDIR <%= ENV.fetch("RUBY_SUBDIR") %>

RUN BUILD_DIR="/tmp/ruby-build" \
 && apt-get update \
 && apt-get -y install wget build-essential zlib1g-dev libssl-dev \
    libreadline6-dev libyaml-dev tzdata <% ENV["RUBY_BUILD_DEPENDENCIES"] %> \
 && mkdir -p "$BUILD_DIR" \
 && cd "$BUILD_DIR" \
 && wget -q "http://cache.ruby-lang.org/pub/ruby/${RUBY_SUBDIR}/ruby-${RUBY_VERSION}.tar.gz" \
 && echo "${RUBY_SHA1SUM}  ruby-${RUBY_VERSION}.tar.gz" | sha1sum -c - \
 && tar xzf "ruby-${RUBY_VERSION}.tar.gz" \
 && cd "ruby-${RUBY_VERSION}" \
 && ./configure --enable-shared --prefix=/usr <% ENV["RUBY_CONFIG_OPTS"] %> \
 && make \
 && make install \
 && cd / \
 && rm -r "$BUILD_DIR" \
 && rm -rf /var/lib/apt/lists/*

<% if ENV["RUBYGEMS_VERSION"] %>
RUN (gem install "rubygems-update:~><%= ENV["RUBYGEMS_VERSION"] %>" --no-document || \
     gem install rubygems-update --version=<%= ENV["RUBYGEMS_VERSION"] %> --no-document) && \
      update_rubygems
<% else %>
RUN gem update --system --no-document
<% end %>
#
RUN gem install "bundler:~><%= ENV.fetch("BUNDLER_VERSION") %>" --no-document --force

ADD test /tmp/test
RUN bats /tmp/test
