FROM quay.io/<%= ENV.fetch('FROM') %>

ENV RUBY_VERSION <%= ENV.fetch('RUBY_VERSION') %>
ENV RUBY_SHA1SUM <%= ENV.fetch('RUBY_SHA1SUM') %>

RUN BUILD_DIR="/tmp/ruby-build" \
 && apt-get update \
 && apt-get -y install wget build-essential zlib1g-dev libssl-dev \
    libreadline6-dev libyaml-dev \
 && mkdir -p "$BUILD_DIR" \
 && cd "$BUILD_DIR" \
 && wget -q "http://cache.ruby-lang.org/pub/ruby/ruby-${RUBY_VERSION}.tar.gz" \
 && echo "${RUBY_SHA1SUM}  ruby-${RUBY_VERSION}.tar.gz" | sha1sum -c - \
 && tar xzf "ruby-${RUBY_VERSION}.tar.gz" \
 && cd "ruby-${RUBY_VERSION}" \
 && ./configure --enable-shared --prefix=/usr \
 && make \
 && make install \
 && cd / \
 && rm -r "$BUILD_DIR" \
 && rm -rf /var/lib/apt/lists/*

RUN gem update --system
RUN gem install --force bundler

ADD test /tmp/test
RUN bats /tmp/test
